title: MariMako Little Lain Blog 
description: A blog in the sea
theme: just-the-docs

url: https://mariimako.github.io/little_lain

# aux_links: # remove if you don't want this link to appear on your pages
#   Template Repository: https://github.com/YOUR-USERNAME/YOUR-SITE-NAME
